name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: docker build -t node-app .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: echo "testing"

  push_to_dockerhub:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_pass}}

      - name: Tag and Push Docker Image
        run: |
          docker tag node-app:latest ${{ secrets.DOCKERHUB_USER }}/node-app:latest
          docker push ${{ secrets.DOCKERHUB_USER }}/node-app:latest

  deploy:
    name: Deploy App
    runs-on: aws-ec2
    needs: push_to_dockerhub
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
